// ------------------------------------------------------------------------------------------------------------------------
//  Copyright (c) ZoomAudits, LLC.
// 
//  Created By: Tim Vidrine
//  Created On: 04/12/2018
// ------------------------------------------------------------------------------------------------------------------------

using Apollo.WebApi.Contracts;

namespace Apollo.WebApi.Messages.Responses
{
    /// <summary>
    /// A response generated by a create end point
    /// </summary>
    /// <inheritdoc/>
    public class CreateWebResponse<T> : BaseWebResponse<T> where T: IDto<T>
    {
        
    }
}